// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegistroCitas.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231210235137_Secundaria")]
    partial class Secundaria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTimezone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FollowingID")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBlock")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsReadonly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceException")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTimezone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Esta crema para piel grasa es humectante y de uso diario. Ayuda a combatir la decoloración, reduciendo visiblemente la apariencia de manchas oscuras en 4 semanas, para que tu piel luzca radiante y con un tono más uniforme.",
                            Image = "https://assets.unileversolutions.com/v1/44022034.png",
                            Name = "POND'S CLARANT B3",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Hidrata la piel de forma rápida gracias a la combinación de ingredientes humectantes y aceite de almendras, que se activan cuando entran en contacto con el agua para absorberse al instante.",
                            Image = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1691762276-1442473.jpg?crop=1xw:1.00xh;center,top&resize=980:*",
                            Name = "Nivea Body Milk Bajo La Ducha",
                            Price = 5m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "La Crema Hidratante de CeraVe, desarrollada por dermatólogos, ofrece una respuesta idónea para aquellas pieles sensibles y secas que buscan una hidratación profunda y duradera. Referente en las pieles más delicadas.",
                            Image = "https://www.cerave.es/-/media/Project/Loreal/BrandSites/CeraVe/Master/Spain/Product/Moisturizers/Moisturizing-cream-16oz.png",
                            Name = "CeraVe Crema Hidratante",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "El aceite esencial de Romero  es un aceite muy perfumado  en AROMATERAPÌA , es la CONCENTRACIÓN ,  crea ambientes frescos y aumenta la CONCENTRACIÓN y la MEMORIA .y su uso tópico como antiséptico.",
                            Image = "https://www.aromesdemorella.com/1077-big_default/aceite-esencial-romero-aromaterapia-12-ml.jpg",
                            Name = "Aceite Esencial Romero Concentración 12 ML",
                            Price = 5m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Celebra la época más mágica del año con el atrayente aroma de la naranja, la canela y la pícea negra. Usa la mezcla de aceites esenciales o disfruta de su fragancia en el jabón de manos.",
                            Image = "https://static.youngliving.com/productimages/large/45222.jpg",
                            Name = "Christmas Spirit",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "El protector solar también es compatible con el mecanismo de reparación del ADN de la piel e incluye la tecnología Oil Control que regula el sebo.",
                            Image = "https://climed.com.do/wp-content/uploads/2021/09/Eucerin-Protector-Solar-en-Gel-Oil-control-SPF-50-X-50mL.jpg",
                            Name = "Gel Cream Oil Control Toque Seco x 50 ML Eucerin",
                            Price = 8m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Se trata de una loción intensificadora para marcar aún tus rizos y conseguir acabar con el encrespamiento. Se aplica sobre el cabello mojado antes de empezar a trabajar en la definición.",
                            Image = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1662113053-n3-hair-perfector-reparador-y-fortalecedor-capilar.jpg?crop=1xw:1.00xh;center,top&resize=980:*",
                            Name = "Olaplex N3 Hair Perfector Reparador y Fortalecedor Capilar",
                            Price = 5m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Si aún no conoces Rulls, solamente decirte que se incorporó al catálogo de la tienda este mismo año y ha sido todo un bombazo. Es Made in Spain y con ingredientes naturales ecológicos certificados. ¡Todo un descubrimiento!",
                            Image = "https://www.sofiablack.com/blog/wp-content/uploads/rulls-styling-curl-gel.webp",
                            Name = "Rulls Moisturizer Curl Cream",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Una crema de peinado que lleva con nosotros desde los inicios de la tienda en 2012, y no deja de maravillar melenas rizadas de tipo 3 y 4. Rizos flexibles, suaves y superhidratados",
                            Image = "https://www.sofiablack.com/blog/wp-content/uploads/aunt-jackies-curl-la-la.webp",
                            Name = "Aunt Jackie's Curl La La",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("EventModel", b =>
                {
                    b.HasOne("Employee", null)
                        .WithMany("Events")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
